"""Coverage for skills/appraise-risk-of-bias/scripts/rob_appraisal.py.

Asserts the rules in specs/001-standards-enforcement-parity/contracts/risk-of-bias.md
across all four instruments. Standard library only.
"""
from __future__ import annotations

import io
import json
import pathlib
import sys
import tempfile
import unittest
from contextlib import redirect_stdout, redirect_stderr
from unittest import mock

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _load import load, fixture  # noqa: E402

ra = load("skills/appraise-risk-of-bias/scripts/rob_appraisal.py")

ALL_INSTRUMENTS = fixture("risk-of-bias.all-instruments.json")


def run(path, *args):
    out, err = io.StringIO(), io.StringIO()
    with mock.patch.object(sys, "argv", ["rob_appraisal.py", str(path), *args]), \
            redirect_stdout(out), redirect_stderr(err):
        code = ra.main()
    return code, out.getvalue(), err.getvalue()


def record(name="risk-of-bias.all-instruments.json"):
    return json.loads(fixture(name).read_text(encoding="utf-8"))


class _Tmp(unittest.TestCase):
    def write(self, rec):
        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        p = pathlib.Path(d.name) / "rec.json"
        p.write_text(json.dumps(rec), encoding="utf-8")
        return p


class TestValidRecord(_Tmp):
    def test_all_four_instruments_pass(self):
        code, out, err = run(ALL_INSTRUMENTS, "--strict")
        self.assertEqual(code, 0, msg=out + err)
        self.assertIn("✅", out)

    def test_emits_both_artifacts(self):
        _, out, _ = run(ALL_INSTRUMENTS)
        self.assertIn("## Appraisal by study", out)
        self.assertIn("## Traffic-light summary", out)

    def test_reports_h_rob_zero(self):
        _, out, _ = run(ALL_INSTRUMENTS)
        self.assertIn("**H_rob: 0**", out)

    def test_states_presence_not_authenticity(self):
        """FR-015: the limitation must appear verbatim, not be implied."""
        _, out, _ = run(ALL_INSTRUMENTS)
        self.assertIn("It cannot establish that a human made the judgment, "
                      "or who that person was.", out)

    def test_carries_provenance(self):
        _, out, _ = run(ALL_INSTRUMENTS)
        self.assertIn("Generated by `rob_appraisal.py`", out)

    def test_traffic_light_is_not_colour_only(self):
        """Every cell pairs a symbol with its text label."""
        _, out, _ = run(ALL_INSTRUMENTS)
        self.assertIn("🟢 low", out)
        self.assertIn("🟡 some concerns", out)
        # And the NOS stars render as a fraction rather than a colour.
        self.assertIn("4/4", out)

    def test_quadas_applicability_rendered_separately(self):
        _, out, _ = run(ALL_INSTRUMENTS)
        self.assertIn("applicability", out)


class TestArtifactPreservesIdentity(_Tmp):
    """Round 7: identity is (study, result), so every artifact row must say which
    result it assesses. Without it, one study appraised for two outcomes renders
    two rows labelled 'R1' carrying different judgments."""

    def test_traffic_light_rows_are_distinguishable(self):
        _, out, _ = run(fixture("risk-of-bias.multi-result.json"))
        light = out.split("## Traffic-light summary", 1)[1]
        rows = [ln for ln in light.splitlines() if ln.startswith("| R1 |")]
        self.assertEqual(len(rows), 2, msg=light)
        self.assertNotEqual(rows[0], rows[1])
        self.assertIn("diagnostic accuracy at 12 months", rows[0])
        self.assertIn("quality of life at 12 months", rows[1])

    def test_every_traffic_light_table_carries_the_result(self):
        """Including the QUADAS-2 applicability table, which is a second grid."""
        _, out, _ = run(ALL_INSTRUMENTS)
        light = out.split("## Traffic-light summary", 1)[1]
        headers = [ln for ln in light.splitlines() if ln.startswith("| Study |")]
        self.assertEqual(len(headers), 5, msg="4 instruments + quadas2 applicability")
        for h in headers:
            self.assertIn("Result assessed", h)

    def test_header_separates_appraisals_from_studies(self):
        """Round 8: len(studies) counts appraisals. Reporting it as a study count
        inflates a manuscript-facing figure the moment a study has two results."""
        _, out, _ = run(fixture("risk-of-bias.multi-result.json"))
        self.assertIn("2 appraisals of 1 study", out)

    def test_header_counts_agree_when_each_study_has_one_result(self):
        _, out, _ = run(fixture("risk-of-bias.contract-example.json"))
        self.assertIn("4 appraisals of 4 studies", out)

    def test_h_rob_is_labelled_as_appraisals(self):
        """It has always counted appraisals: a human confirms a judgment about one
        result, not a study wholesale. Only the noun was wrong."""
        _, out, _ = run(fixture("risk-of-bias.unconfirmed-study.json"))
        self.assertIn("**H_rob: 1** appraisal awaiting", out)

    def test_violations_name_the_appraisal_not_just_the_study(self):
        """Round 9: with two appraisals of one study and only one at fault,
        'study R1' cannot tell the reviewer which judgment to go and fix."""
        code, out, _ = run(
            fixture("risk-of-bias.multi-result-partial-confirm.json"), "--strict")
        self.assertEqual(code, 1)
        faults = [ln for ln in out.splitlines() if ln.startswith("- study R1")]
        self.assertEqual(len(faults), 1, msg=out)
        self.assertIn("quality of life at 12 months", faults[0])
        self.assertNotIn("diagnostic accuracy", faults[0])
        self.assertIn("**H_rob: 1**", out)

    def test_every_violation_carries_the_result(self):
        """Not only the confirmation gate — the same ambiguity affects any
        per-appraisal violation once judgments differ by result."""
        for name in ("risk-of-bias.wrong-instrument.json",
                     "risk-of-bias.missing-domain.json",
                     "risk-of-bias.overall-too-favourable.json",
                     "risk-of-bias.nos-band-mismatch.json",
                     "risk-of-bias.no-info-but-low.json"):
            with self.subTest(fixture=name):
                _, out, _ = run(fixture(name))
                for ln in out.splitlines():
                    if ln.startswith("- study "):
                        self.assertIn("(result: ", ln)

    def test_result_rendered_even_when_the_instrument_mismatches(self):
        """The mismatch path skips domain validation, so it renders separately and
        would otherwise miss the column."""
        _, out, _ = run(fixture("risk-of-bias.wrong-instrument.json"))
        light = out.split("## Traffic-light summary", 1)[1]
        for ln in light.splitlines():
            if ln.startswith("| R1 |"):
                self.assertIn("diagnostic accuracy at 12 months", ln)


class TestInstrumentMatching(_Tmp):
    def test_wrong_instrument_for_design(self):
        code, out, _ = run(fixture("risk-of-bias.wrong-instrument.json"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("calls for rob2", out)

    def test_every_design_maps_to_its_instrument(self):
        self.assertEqual(ra.DESIGN_INSTRUMENT, {
            "rct": "rob2", "nrsi": "robins_i",
            "observational": "nos", "dta": "quadas2"})

    def test_domain_counts_match_the_instruments(self):
        self.assertEqual(len(ra.DOMAINS["rob2"]), 5)
        self.assertEqual(len(ra.DOMAINS["robins_i"]), 7)
        self.assertEqual(len(ra.DOMAINS["nos"]), 3)
        self.assertEqual(len(ra.DOMAINS["quadas2"]), 4)


class TestMalformed(_Tmp):
    def assert_malformed(self, name, *needles):
        code, out, err = run(fixture(name), "--strict")
        self.assertEqual(code, 2, msg=f"expected exit 2 for {name}, got {code}")
        for n in needles:
            self.assertIn(n, err)
        self.assertNotIn("## Appraisal by study", out)

    def test_bad_vocabulary(self):
        self.assert_malformed("risk-of-bias.bad-vocabulary.json", "probably_fine")

    def test_unknown_domain_key(self):
        self.assert_malformed("risk-of-bias.unknown-domain.json", "blinding", "unrecognised key")

    def test_duplicate_id(self):
        """Identity is now (study, result): the same study appraised twice for the
        SAME result is still ambiguous and rejected."""
        self.assert_malformed("risk-of-bias.duplicate-id.json", "duplicate appraisal")

    def test_empty_studies(self):
        self.assert_malformed("risk-of-bias.empty-studies.json", "nothing to appraise")

    def test_missing_version(self):
        self.assert_malformed("risk-of-bias.no-version.json", "schema_version")

    def test_nos_stars_over_maximum(self):
        self.assert_malformed("risk-of-bias.nos-over-max.json", "between 0 and 2")

    def test_invalid_json(self):
        out, err = io.StringIO(), io.StringIO()
        with mock.patch.object(sys, "argv", ["rob_appraisal.py"]), \
                mock.patch.object(sys, "stdin", io.StringIO("{oops")), \
                redirect_stdout(out), redirect_stderr(err):
            code = ra.main()
        self.assertEqual(code, 2)
        self.assertIn("not valid JSON", err.getvalue())


class TestViolations(_Tmp):
    def test_missing_domain_is_a_violation_not_malformed(self):
        """Absent domain -> exit 1 and named; misspelled domain -> exit 2. The
        distinction stops a typo being 'fixed' by adding a domain already present."""
        code, out, _ = run(fixture("risk-of-bias.missing-domain.json"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("measurement", out)
        self.assertIn("absent", out)

    def test_overall_more_favourable_than_worst_domain(self):
        code, out, _ = run(fixture("risk-of-bias.overall-too-favourable.json"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("more favourable than its", out)
        self.assertIn("missing_data", out)

    def test_overall_override_accepted_with_justification(self):
        rec = record("risk-of-bias.overall-too-favourable.json")
        rec["studies"][0]["overall_justification"] = \
            "Attrition was balanced across arms and a sensitivity analysis was unchanged."
        code, out, _ = run(self.write(rec), "--strict")
        self.assertEqual(code, 0, msg=out)

    def test_nos_band_mismatch_flagged(self):
        code, out, _ = run(fixture("risk-of-bias.nos-band-mismatch.json"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("bands as", out)
        self.assertIn("conventional", out)

    def test_no_information_cannot_yield_overall_low(self):
        """Absence of evidence is not evidence of low risk."""
        code, out, _ = run(fixture("risk-of-bias.no-info-but-low.json"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("no information", out)
        self.assertIn("absence of evidence is not evidence of low risk", out)

    def test_violation_without_strict_exits_zero(self):
        code, out, _ = run(fixture("risk-of-bias.overall-too-favourable.json"))
        self.assertEqual(code, 0)
        self.assertIn("issue(s)", out)


class TestHumanGate(_Tmp):
    def test_unconfirmed_study_counted_and_reported(self):
        code, out, _ = run(fixture("risk-of-bias.unconfirmed-study.json"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("**H_rob: 1**", out)
        self.assertIn("no human confirmation recorded", out)
        self.assertIn("⚠️ **not confirmed**", out)

    def test_blank_confirmation_does_not_satisfy_the_gate(self):
        """Whitespace is not a confirmation."""
        rec = record()
        rec["studies"][0]["confirmed_by"] = "   "
        code, out, _ = run(self.write(rec), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("**H_rob: 1**", out)

    def test_missing_date_does_not_satisfy_the_gate(self):
        rec = record()
        del rec["studies"][0]["confirmed_at"]
        code, out, _ = run(self.write(rec), "--strict")
        self.assertEqual(code, 1)


class TestNosBanding(unittest.TestCase):
    def test_bands(self):
        for total, band in [(9, "low"), (7, "low"), (6, "moderate"),
                            (4, "moderate"), (3, "high"), (0, "high")]:
            with self.subTest(total=total):
                self.assertEqual(ra.nos_band(total), band)


if __name__ == "__main__":
    unittest.main()


class TestEvidenceIsValidated(_Tmp):
    """Round 10: `s.get("evidence", {}) or {}` accepted anything. A string, a list
    and an int all exited 0 under --strict, then backed a confirmed_rob rating."""

    def with_evidence(self, ev, drop=False):
        rec = record("risk-of-bias.contract-example.json")
        if drop:
            rec["studies"][0].pop("evidence", None)
        else:
            rec["studies"][0]["evidence"] = ev
        return self.write(rec)

    def test_wrong_type_is_malformed_not_clean(self):
        for ev in ("not an object", ["a", "b"], 42, True):
            with self.subTest(evidence=ev):
                code, _, err = run(self.with_evidence(ev), "--strict")
                self.assertEqual(code, 2)
                self.assertIn("evidence", err)

    def test_explicit_null_is_not_treated_as_absent(self):
        code, _, err = run(self.with_evidence(None), "--strict")
        self.assertEqual(code, 2)
        self.assertIn("evidence", err)

    def test_non_string_supporting_text_is_rejected(self):
        code, _, err = run(self.with_evidence({"randomization": 123}), "--strict")
        self.assertEqual(code, 2)
        self.assertIn("randomization", err)

    def test_blank_supporting_text_is_rejected(self):
        """Whitespace quotes nothing — same rule the confirmation gate follows."""
        code, _, _ = run(self.with_evidence({"randomization": "   "}), "--strict")
        self.assertEqual(code, 2)

    def test_key_must_be_a_domain_of_that_instrument(self):
        code, _, err = run(self.with_evidence({"blinding": "p.4"}), "--strict")
        self.assertEqual(code, 2)
        self.assertIn("blinding", err)

    def test_absent_and_empty_remain_legal(self):
        """Evidence is optional; the fix must not make it mandatory."""
        self.assertEqual(run(self.with_evidence(None, drop=True), "--strict")[0], 0)
        self.assertEqual(run(self.with_evidence({}), "--strict")[0], 0)

    def test_valid_evidence_still_passes(self):
        code, out, _ = run(self.with_evidence(
            {"randomization": "p.4: 'sealed opaque envelopes'"}), "--strict")
        self.assertEqual(code, 0, msg=out)

    def test_validated_on_the_instrument_mismatch_path_too(self):
        """That path returns early, before domain validation — it needs its own
        call, and its keys cannot be checked against the wrong instrument."""
        rec = record("risk-of-bias.wrong-instrument.json")
        rec["studies"][0]["evidence"] = "not an object"
        code, _, err = run(self.write(rec), "--strict")
        self.assertEqual(code, 2)
        self.assertIn("evidence", err)
