"""Coverage for skills/validate-evidence/scripts/grade_profile.py.

Asserts the rules in specs/001-standards-enforcement-parity/contracts/grade-profile.md.
Each defect fixture carries exactly ONE defect, so a failure identifies its own cause.
Standard library only.
"""
from __future__ import annotations

import io
import json
import pathlib
import sys
import unittest
from contextlib import redirect_stdout, redirect_stderr
from unittest import mock

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _load import load, fixture  # noqa: E402

gp = load("skills/validate-evidence/scripts/grade_profile.py")

VALID = fixture("grade-profile.valid.json")
ROB_VALID = fixture("risk-of-bias.valid.json")
ROB_HIGH = fixture("risk-of-bias.mostly-high.json")
ROB_UNCONFIRMED = fixture("risk-of-bias.unconfirmed.json")


def run(record_path, *args):
    """Invoke main() and return (exit_code, stdout, stderr)."""
    out, err = io.StringIO(), io.StringIO()
    argv = ["grade_profile.py", str(record_path), *args]
    with mock.patch.object(sys, "argv", argv), redirect_stdout(out), redirect_stderr(err):
        code = gp.main()
    return code, out.getvalue(), err.getvalue()


def load_record(name="grade-profile.valid.json"):
    return json.loads(fixture(name).read_text(encoding="utf-8"))


class TestValidRecord(unittest.TestCase):
    def test_valid_record_passes_with_rob(self):
        code, out, err = run(VALID, "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 0, msg=out + err)
        self.assertIn("✅", out)

    def test_emits_both_artifacts(self):
        _, out, _ = run(VALID, "--rob", str(ROB_VALID))
        self.assertIn("## Evidence profile", out)
        self.assertIn("## Summary of findings", out)

    def test_declares_synthesis_mode(self):
        _, out, _ = run(VALID, "--rob", str(ROB_VALID))
        self.assertIn("protocol outcomes", out)

    def test_theme_mode_is_labelled_as_an_adaptation(self):
        rec = load_record()
        rec["synthesis_mode"] = "theme"
        _, out, _ = run(self._tmp(rec, "theme.json"), "--rob", str(ROB_VALID))
        self.assertIn("SWiM adaptation", out)
        self.assertIn("synthesis themes", out)
        self.assertIn("not GRADE as published", out)

    def test_carries_provenance_line(self):
        _, out, _ = run(VALID, "--rob", str(ROB_VALID))
        self.assertIn("Generated by `grade_profile.py`", out)

    def test_states_what_it_cannot_verify(self):
        _, out, _ = run(VALID, "--rob", str(ROB_VALID))
        self.assertIn("cannot verify that a domain judgment was the", out)

    def _tmp(self, rec, name):
        import tempfile
        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        p = pathlib.Path(d.name) / name
        p.write_text(json.dumps(rec), encoding="utf-8")
        return p


class TestGoldenOutput(unittest.TestCase):
    """Pin the generated artifact so a refactor cannot quietly change what reviewers see.

    The provenance line embeds the invocation's source path, so the comparison
    covers everything above it.
    """

    def test_generated_artifact_matches_golden(self):
        _, out, _ = run(VALID, "--rob", str(ROB_VALID))
        actual = out.split("\n---\n\n*Generated by")[0].rstrip() + "\n"
        expected = fixture("grade-profile.valid.golden.md").read_text(encoding="utf-8")
        self.assertEqual(actual, expected)


class TestMalformedInput(unittest.TestCase):
    """Exit 2 — the record cannot be read. Distinct from a review being wrong."""

    def assert_malformed(self, name, *needles):
        code, out, err = run(fixture(name), "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 2, msg=f"expected exit 2 for {name}, got {code}")
        for n in needles:
            self.assertIn(n, err)
        # A record that cannot be read must not produce an authoritative-looking artifact.
        self.assertNotIn("## Evidence profile", out)

    def test_missing_schema_version(self):
        self.assert_malformed("grade-profile.no-version.json", "schema_version")

    def test_typo_domain_is_malformed_not_missing(self):
        """The distinction that matters most.

        A misspelled domain key reported as a *missing domain* would send the
        reviewer to add a domain they already wrote, and the typo would survive.
        """
        code, _, err = run(fixture("grade-profile.typo-domain.json"), "--strict")
        self.assertEqual(code, 2)
        self.assertIn("indirectnes", err)
        self.assertIn("unrecognised key", err)
        self.assertNotIn("missing downgrade domain", err)

    def test_aggregate_certainty_rejected(self):
        self.assert_malformed("grade-profile.aggregate-certainty.json",
                              "overall_certainty", "aggregated")

    def test_illegal_upgrade_key_rejected(self):
        self.assert_malformed("grade-profile.illegal-upgrade.json",
                              "importance_of_findings", "unrecognised key")

    def test_quoted_count_rejected(self):
        self.assert_malformed("grade-profile.quoted-count.json", "must be a JSON number")

    def test_empty_results_rejected(self):
        self.assert_malformed("grade-profile.empty-results.json", "nothing to check")

    def test_duplicate_study_id_rejected(self):
        self.assert_malformed("grade-profile.duplicate-study-id.json", "duplicate identifier")

    def test_invalid_json_exits_two(self):
        out, err = io.StringIO(), io.StringIO()
        stdin = io.StringIO("{not json")
        with mock.patch.object(sys, "argv", ["grade_profile.py"]), \
                mock.patch.object(sys, "stdin", stdin), \
                redirect_stdout(out), redirect_stderr(err):
            code = gp.main()
        self.assertEqual(code, 2)
        self.assertIn("not valid JSON", err.getvalue())


class TestRuleViolations(unittest.TestCase):
    """Exit 1 under --strict — the record is readable but the grading is wrong."""

    def test_missing_domain_named_not_defaulted(self):
        code, out, _ = run(fixture("grade-profile.missing-domain.json"),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("imprecision", out)
        self.assertIn("not a judgment of 'no concern'", out)

    def test_bad_arithmetic_reports_both_sides(self):
        code, out, _ = run(fixture("grade-profile.bad-arithmetic.json"),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 1)
        # The message must carry the numbers, not merely name the rule.
        self.assertIn("moderate(3)", out)
        self.assertIn("high(4)", out)

    def test_minority_rct_starting_level_flagged(self):
        code, out, _ = run(fixture("grade-profile.minority-rct.json"),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("predominant design", out)
        self.assertIn("observational", out)

    def test_starting_level_deviation_allowed_with_justification(self):
        rec = load_record("grade-profile.minority-rct.json")
        rec["results"][0]["starting_level_justification"] = \
            "The single randomized trial is decisive and the observational studies are supportive."
        code, out, _ = run(self._write(rec), "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 0, msg=out)

    def test_violation_without_strict_exits_zero(self):
        code, out, _ = run(fixture("grade-profile.bad-arithmetic.json"), "--rob", str(ROB_VALID))
        self.assertEqual(code, 0)
        self.assertIn("issue(s)", out)

    def _write(self, rec):
        import tempfile
        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        p = pathlib.Path(d.name) / "rec.json"
        p.write_text(json.dumps(rec), encoding="utf-8")
        return p


class TestUpgradeLegality(unittest.TestCase):
    def _rec_with_upgrade(self, design, downgrade):
        rec = load_record()
        r = rec["results"][0]
        r["design_mix"] = {"rct": 0, "nrsi": 0, "observational": 4, "case_series": 0} \
            if design == "observational" else {"rct": 4, "nrsi": 0, "observational": 0, "case_series": 0}
        r["starting_level"] = "low" if design == "observational" else "high"
        for name in gp.DOMAINS:
            r["domains"][name]["rating"] = -1 if (downgrade and name == "inconsistency") else 0
        r["upgrades"] = {"large_effect": 1, "dose_response": 0, "opposing_confounding": 0}
        start = gp.LEVELS[r["starting_level"]]
        r["final"] = gp.LEVEL_NAMES[max(1, min(4, start + (-1 if downgrade else 0) + 1))]
        return rec

    def test_upgrade_on_observational_with_no_downgrade_is_legal(self):
        code, out, _ = run(self._write(self._rec_with_upgrade("observational", False)),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 0, msg=out)

    def test_upgrade_on_randomized_body_is_flagged(self):
        code, out, _ = run(self._write(self._rec_with_upgrade("rct", False)),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("only for non-randomized evidence", out)

    def test_upgrade_over_a_downgrade_is_flagged(self):
        code, out, _ = run(self._write(self._rec_with_upgrade("observational", True)),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("unresolved serious concerns", out)

    def _write(self, rec):
        import tempfile
        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        p = pathlib.Path(d.name) / "rec.json"
        p.write_text(json.dumps(rec), encoding="utf-8")
        return p


class TestRiskOfBiasBasis(unittest.TestCase):
    def _with_basis(self, basis, review_type, disclosed=None):
        rec = load_record()
        rec["review_type"] = review_type
        rec["results"][0]["domains"]["risk_of_bias"]["basis"] = basis
        if disclosed:
            rec["streamlined_method_disclosed"] = disclosed
        import tempfile
        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        p = pathlib.Path(d.name) / "rec.json"
        p.write_text(json.dumps(rec), encoding="utf-8")
        return p

    def test_confirmed_basis_without_rob_is_a_violation(self):
        """A basis claim unaccompanied by evidence is not accepted on trust."""
        code, out, _ = run(VALID, "--strict")
        self.assertEqual(code, 1)
        self.assertIn("cannot be", out)
        self.assertIn("--rob", out)

    def test_heuristic_rejected_for_systematic(self):
        code, out, _ = run(self._with_basis("heuristic", "systematic"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("requires confirmed appraisal", out)

    def test_heuristic_rejected_for_umbrella(self):
        code, out, _ = run(self._with_basis("heuristic", "umbrella"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("requires confirmed appraisal", out)

    def test_heuristic_allowed_for_rapid_when_disclosed(self):
        path = self._with_basis("heuristic", "rapid",
                                disclosed="Single-reviewer screening; two databases only.")
        code, out, _ = run(path, "--strict")
        self.assertEqual(code, 0, msg=out)

    def test_heuristic_rejected_for_rapid_without_disclosure(self):
        code, out, _ = run(self._with_basis("heuristic", "rapid"), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("must be stated", out)

    def test_heuristic_output_marked_provisional(self):
        _, out, _ = run(self._with_basis("heuristic", "rapid", disclosed="Streamlined."), )
        self.assertIn("PROVISIONAL", out)

    def test_unknown_basis_is_malformed(self):
        code, _, err = run(self._with_basis("vibes", "systematic"), "--strict")
        self.assertEqual(code, 2)
        self.assertIn("basis", err)


class TestTraceability(unittest.TestCase):
    def test_case_mismatch_is_unresolved_not_matched(self):
        code, out, _ = run(fixture("grade-profile.case-mismatch.json"),
                           "--rob", str(ROB_VALID), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("not found in the appraisal record", out)
        # The near-miss is surfaced as a hint, never silently reconciled.
        self.assertIn("matched exactly", out)

    def test_unconfirmed_study_cannot_back_confirmed_basis(self):
        code, out, _ = run(VALID, "--rob", str(ROB_UNCONFIRMED), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("no human confirmation", out)

    def test_incoherent_body_judgment_flagged(self):
        code, out, _ = run(fixture("grade-profile.incoherent-rob.json"),
                           "--rob", str(ROB_HIGH), "--strict")
        self.assertEqual(code, 1)
        self.assertIn("high risk", out)
        self.assertIn("coherence_justification", out)

    def test_coherence_override_accepted(self):
        rec = load_record("grade-profile.incoherent-rob.json")
        rec["results"][0]["domains"]["risk_of_bias"]["coherence_justification"] = \
            "The high-risk studies contribute little weight to this outcome."
        import tempfile
        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        p = pathlib.Path(d.name) / "rec.json"
        p.write_text(json.dumps(rec), encoding="utf-8")
        code, out, _ = run(p, "--rob", str(ROB_HIGH), "--strict")
        self.assertEqual(code, 0, msg=out)


class TestPredominantDesign(unittest.TestCase):
    def test_majority_wins(self):
        self.assertEqual(gp.predominant_design(
            {"rct": 1, "nrsi": 0, "observational": 8, "case_series": 0}), "observational")

    def test_tie_resolves_to_the_weaker_design(self):
        """A tie must not be resolved in favour of the stronger design.

        Resolving 4 RCTs vs 4 cohorts to 'rct' would start the body two levels
        higher on no evidence at all.
        """
        self.assertEqual(gp.predominant_design(
            {"rct": 4, "nrsi": 0, "observational": 4, "case_series": 0}), "observational")


class TestCoercion(unittest.TestCase):
    """Must agree with prisma_flow.py — see contracts/cli-contract.md."""

    def test_rejects_bool(self):
        with self.assertRaises(gp.InputError):
            gp._int(True, "x")

    def test_rejects_numeric_string(self):
        with self.assertRaises(gp.InputError):
            gp._int("3", "x")

    def test_rejects_non_integral_float(self):
        with self.assertRaises(gp.InputError):
            gp._int(3.5, "x")

    def test_rejects_negative(self):
        with self.assertRaises(gp.InputError):
            gp._int(-1, "x")

    def test_rejects_non_finite(self):
        for bad in (float("nan"), float("inf")):
            with self.subTest(value=bad), self.assertRaises(gp.InputError):
                gp._int(bad, "x")

    def test_rating_rejects_half_steps(self):
        for bad in (-0.5, -3, 1, True):
            with self.subTest(value=bad), self.assertRaises(gp.InputError):
                gp._rating(bad, "x")


if __name__ == "__main__":
    unittest.main()
